openapi: 3.0.3
info:
  title: RAGE Search Engine API
  version: 1.0.0
  description: |
    **Search Engine** provides hybrid search capabilities combining:
    - Vector similarity search (1536-dim embeddings)
    - Semantic search with query understanding
    - BM25 keyword search for exact matches
    - Configurable search strategies
    - Re-ranking for result optimization

servers:
  - url: http://localhost:8008
    description: Local development
  - url: http://search-engine:8008
    description: Docker/Podman internal network

paths:
  /api/v1/search/hybrid:
    post:
      summary: Hybrid search
      description: Combined vector + semantic + BM25 search with re-ranking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                user_id:
                  type: string
                  description: For ACL filtering
                top_k:
                  type: integer
                  default: 10
                  maximum: 50
                engines:
                  type: array
                  items:
                    type: string
                    enum: [vector, semantic, bm25]
                  default: [vector, semantic, bm25]
                rerank:
                  type: boolean
                  default: true
                filters:
                  type: object
                  properties:
                    source_types:
                      type: array
                      items:
                        type: string
                    date_range:
                      type: object
                      properties:
                        from:
                          type: string
                          format: date
                        to:
                          type: string
                          format: date
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                  - total_found
                  - latency_ms
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required:
                        - document_id
                        - chunk_id
                        - score
                        - text
                      properties:
                        document_id:
                          type: string
                        chunk_id:
                          type: string
                        score:
                          type: number
                          format: float
                        text:
                          type: string
                        metadata:
                          type: object
                  total_found:
                    type: integer
                  latency_ms:
                    type: integer
                  search_metadata:
                    type: object
                    properties:
                      engines_used:
                        type: array
                        items:
                          type: string
                      acl_filtered:
                        type: integer
                      reranked:
                        type: boolean

  /api/v1/search/vector:
    post:
      summary: Vector-only search
      description: Pure vector similarity search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                top_k:
                  type: integer
                  default: 10
      responses:
        '200':
          description: Vector search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object

  /api/v1/search/semantic:
    post:
      summary: Semantic search
      description: Context-aware semantic search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                context:
                  type: string
      responses:
        '200':
          description: Semantic search results

  /api/v1/search/keyword:
    post:
      summary: BM25 keyword search
      description: Traditional keyword-based search for exact matches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                top_k:
                  type: integer
      responses:
        '200':
          description: Keyword search results

components:
  securitySchemes:
    ServiceAuth:
      type: http
      scheme: bearer

security:
  - ServiceAuth: []
